import { useEffect, useMemo, useState } from 'react'

const card={background:'#12121A',border:'1px solid rgba(255,255,255,.08)',borderRadius:16,padding:18}
const money=n=>Number.isFinite(Number(n))?`$${Number(n).toFixed(4)}`:'—'
const num=n=>Number(n||0).toLocaleString()
function Metric({label,value,hint}){return <div style={card}><div style={{fontSize:12,color:'#8A849E',marginBottom:8}}>{label}</div><div style={{fontSize:28,fontWeight:760,color:'#F4F1FF'}}>{value}</div>{hint&&<div style={{fontSize:11,color:'#69647C',marginTop:6,lineHeight:1.45}}>{hint}</div>}</div>}

export default function AdminCosts({onClose}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/recall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'admin_costs'})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Could not load cost data');setData(b)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const rows=useMemo(()=>data?.recent||[],[data])
 return <div style={{minHeight:'100dvh',background:'#0A0A12',color:'#F4F1FF',padding:24,fontFamily:"'Inter',sans-serif"}}><div style={{maxWidth:1250,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:24}}><div><div style={{fontSize:12,color:'#7F78A7',fontWeight:800,letterSpacing:1.1,textTransform:'uppercase'}}>Wani Admin</div><h1 style={{margin:'6px 0 0',fontSize:28}}>Cost Management</h1></div><div style={{display:'flex',gap:8}}><button onClick={load} style={{padding:'9px 14px',borderRadius:10,border:'1px solid #343044',background:'#171522',color:'#D8D3EA'}}>Refresh</button><button onClick={onClose} style={{padding:'9px 14px',borderRadius:10,border:'1px solid #4F46E5',background:'#4F46E5',color:'#fff'}}>Admin Home</button></div></div>
  {error&&<div style={{...card,borderColor:'rgba(239,68,68,.4)',color:'#FCA5A5',marginBottom:18}}>{error}</div>}
  {loading&&!data?<div style={{color:'#8A849E'}}>Loading cost telemetry…</div>:data&&<>
   <div style={{...card,marginBottom:14,borderColor:'rgba(167,139,250,.25)',background:'#11101A'}}><div style={{fontSize:12,color:'#C4B5FD',fontWeight:750,marginBottom:5}}>What this dashboard measures</div><div style={{fontSize:12,color:'#8A849E',lineHeight:1.55}}>These are actual persisted Anthropic Claude Sonnet token costs from Wani responses. Groq, Tavily and OpenAI spend is not yet fully persisted, so this dashboard deliberately does not label the values as total Wani cost.</div></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(175px,1fr))',gap:12,marginBottom:18}}><Metric label="Sonnet cost today" value={money(data.summary.costToday)}/><Metric label="Sonnet cost this month" value={money(data.summary.costMonth)}/><Metric label="Recorded calls today" value={num(data.summary.callsToday)}/><Metric label="Recorded calls this month" value={num(data.summary.callsMonth)}/><Metric label="Input tokens this month" value={num(data.summary.inputTokensMonth)}/><Metric label="Output tokens this month" value={num(data.summary.outputTokensMonth)}/><Metric label="Avg Sonnet cost / call" value={money(data.summary.avgCostMonth)}/></div>
   <div style={{...card,padding:0,overflow:'hidden'}}><div style={{padding:'16px 18px',fontWeight:750}}>Recent cost records</div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:850}}><thead><tr style={{background:'#171522'}}>{['When','Intent','Model','Input','Output','Cost'].map(h=><th key={h} style={{textAlign:'left',padding:'11px 14px',fontSize:11,color:'#8A849E',textTransform:'uppercase',borderBottom:'1px solid #2A2736'}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.request_id||i} style={{borderBottom:'1px solid rgba(255,255,255,.05)'}}><td style={{padding:'12px 14px',fontSize:12}}>{r.created_at?new Date(r.created_at).toLocaleString():'—'}</td><td style={{padding:'12px 14px',fontSize:12}}>{r.intent||'—'}</td><td style={{padding:'12px 14px',fontSize:12,color:'#C4B5FD'}}>{r.model||r.provider||'—'}</td><td style={{padding:'12px 14px',fontSize:12}}>{num(r.input_tokens)}</td><td style={{padding:'12px 14px',fontSize:12}}>{num(r.output_tokens)}</td><td style={{padding:'12px 14px',fontSize:12,fontWeight:750}}>{money(r.anthropic_cost_usd)}</td></tr>)}{!rows.length&&<tr><td colSpan="6" style={{padding:22,textAlign:'center',color:'#77718B'}}>No Sonnet cost records yet.</td></tr>}</tbody></table></div></div>
  </>}
 </div></div>
}
