import { useEffect, useMemo, useState } from 'react'

const card={background:'#12121A',border:'1px solid rgba(255,255,255,.08)',borderRadius:16,padding:18}

export default function AdminKnowledge({onClose}){
 const [pending,setPending]=useState([]),[global,setGlobal]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [q,s]=await Promise.all([
  fetch('/api/recall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'knowledge_review_queue'})}),
  fetch('/api/recall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'knowledge_snapshot'})})]);
  const qb=await q.json().catch(()=>({})),sb=await s.json().catch(()=>({}));if(!q.ok)throw new Error(qb.error||'Could not load review queue');if(!s.ok)throw new Error(sb.error||'Could not load knowledge library');setPending(qb.entries||[]);setGlobal(sb.globalEntries||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const review=async(entry,decision)=>{if(decision==='reject'&&!window.confirm('Reject this knowledge candidate?'))return;setBusy(entry.id);setError('');try{const r=await fetch('/api/recall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'knowledge_review',id:entry.id,decision,module:entry.module||'',topic:entry.topic||'',object:entry.object||'',finding:entry.finding||'',note:''})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Review failed');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const modules=useMemo(()=>{const m={};global.forEach(x=>{const k=x.module||'Unclassified';m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])},[global])
 return <div style={{minHeight:'100dvh',background:'#0A0A12',color:'#F4F1FF',padding:24,fontFamily:"'Inter',sans-serif"}}><div style={{maxWidth:1300,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:24}}><div><div style={{fontSize:12,color:'#7F78A7',fontWeight:800,letterSpacing:1.1,textTransform:'uppercase'}}>Wani Admin</div><h1 style={{margin:'6px 0 0',fontSize:28}}>Knowledge Management</h1></div><div style={{display:'flex',gap:8}}><button onClick={load} style={{padding:'9px 14px',borderRadius:10,border:'1px solid #343044',background:'#171522',color:'#D8D3EA'}}>Refresh</button><button onClick={onClose} style={{padding:'9px 14px',borderRadius:10,border:'1px solid #4F46E5',background:'#4F46E5',color:'#fff'}}>Admin Home</button></div></div>
  {error&&<div style={{...card,borderColor:'rgba(239,68,68,.4)',color:'#FCA5A5',marginBottom:18}}>{error}</div>}
  {loading?<div style={{color:'#8A849E'}}>Loading knowledge…</div>:<>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginBottom:18}}><div style={card}><div style={{fontSize:12,color:'#8A849E'}}>Pending review</div><div style={{fontSize:28,fontWeight:760,marginTop:8,color:'#FCD34D'}}>{pending.length}</div></div><div style={card}><div style={{fontSize:12,color:'#8A849E'}}>Global knowledge</div><div style={{fontSize:28,fontWeight:760,marginTop:8,color:'#C4B5FD'}}>{global.length}</div></div><div style={card}><div style={{fontSize:12,color:'#8A849E'}}>Modules represented</div><div style={{fontSize:28,fontWeight:760,marginTop:8}}>{modules.length}</div></div></div>
   <div style={{...card,marginBottom:16}}><div style={{fontWeight:750,marginBottom:14}}>Pending consultant corrections</div>{pending.length===0?<div style={{color:'#77718B',fontSize:13}}>Nothing waiting for review.</div>:pending.map(e=><div key={e.id} style={{padding:'14px 0',borderBottom:'1px solid rgba(255,255,255,.055)'}}><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{flex:1,minWidth:240}}><div style={{fontSize:11,color:'#8B7CF6',fontWeight:750,marginBottom:5}}>{[e.module,e.topic,e.object].filter(Boolean).join(' · ')||'Unclassified SAP knowledge'}</div><div style={{fontSize:13,lineHeight:1.55,color:'#D6D1E3'}}>{e.finding||e.content||'No finding text'}</div><div style={{fontSize:10,color:'#655F70',marginTop:7}}>{e.user_email||e.email||e.source_email||''}</div></div><div style={{display:'flex',gap:7}}><button disabled={busy===e.id} onClick={()=>review(e,'approve')} style={{border:'1px solid #2F6E49',background:'#10251A',color:'#86EFAC',borderRadius:8,padding:'7px 10px'}}>Approve</button><button disabled={busy===e.id} onClick={()=>review(e,'reject')} style={{border:'1px solid #71343D',background:'#281316',color:'#FCA5A5',borderRadius:8,padding:'7px 10px'}}>Reject</button></div></div></div>)}</div>
   <div style={{display:'grid',gridTemplateColumns:'minmax(220px,.35fr) minmax(0,1fr)',gap:14}}><div style={card}><div style={{fontWeight:750,marginBottom:12}}>Global library by module</div>{modules.map(([m,n])=><div key={m} style={{display:'flex',justifyContent:'space-between',padding:'8px 0',fontSize:12,borderBottom:'1px solid rgba(255,255,255,.04)'}}><span style={{color:'#A9A4BA'}}>{m}</span><span style={{color:'#C4B5FD',fontWeight:750}}>{n}</span></div>)}</div><div style={{...card,padding:0,overflow:'hidden'}}><div style={{padding:'16px 18px',fontWeight:750}}>Global knowledge library</div><div style={{maxHeight:520,overflowY:'auto'}}>{global.map(e=><div key={e.id} style={{padding:'14px 18px',borderTop:'1px solid rgba(255,255,255,.05)'}}><div style={{fontSize:11,color:'#8B7CF6',fontWeight:750}}>{[e.module,e.topic,e.object].filter(Boolean).join(' · ')||'Unclassified'}</div><div style={{fontSize:12,lineHeight:1.5,color:'#CFCADA',marginTop:5}}>{e.finding}</div></div>)}{!global.length&&<div style={{padding:20,color:'#77718B'}}>No global entries yet.</div>}</div></div></div>
  </>}
 </div></div>
}
